### ISSUE TITLE
Example of Eth to Bitcoin?

### ISSUE THREAD

**Issue by peterchen16** [republicprotocol/eth-atomic-swap#7]
Hi, can you guys provide a code example of how to use the eth to bitcoin swap?

**Comment by loongy** [comment]
@peterchen16 this repository is actually deprecated in favour of our automated trading software that does everything for you. We are keeping it here for reference, but are not actively supporting it.

**Comment by peterchen16** [comment]
where is the software?

**Comment by loongy** [comment]
it is not yet publicly available.

**Comment by MikeD123** [comment]
Hey guys! 

Any update on the swap creation for Bitcoin? I wasn't sure if you're just doing a 1:1 atomic swap like with the initial implementation for ETH:ERC-20, etc... It's also possible that you're just using ☢️🔀☢️to collateralize and then mint a `WBTC`?

Would be great to see what the implementation looks like either way.

So psyched for you guys. Nice work. 

Also... 'Straya!
🇦🇺🇦🇺🇦🇺
